#!/bin/bash

source $(dirname $0)/panel_config
source $(dirname $0)/ps

while read -r line ; do
    case $line in
	V*)
            volume
	    ;;
        C*)
	    network
	    freeram
	    cputemp
	    checkupdates
	    volume
	    DATE=$(date -u +%d/%m/%y)
	    TIME=$(date +%H:%M)
            ;;
	W*)
		wm_infos=""
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
		               [OFU]*)
	                        # active desktop
        	                wm_infos="$wm_infos %{U$COLOR_ACTIVE}%{+u}   %{-u}"
        	                ;;
        	            o*)
        	                # inactive but occupied desktop
        	                wm_infos="$wm_infos %{U$COLOR_OCCUPIED}%{+u}   %{-u}"
        	                ;;
        	            f*)
        	                # inactive desktop
        	                wm_infos="$wm_infos    "
        	                ;;
        	            u*)
        	                # urgent desktop
        	                wm_infos="$wm_infos %{U$COLOR_URGENT}%{+u}   %{-u}"
        	                ;;
        	            L*)
        	                # layout
#       	                 layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
        	                wm_infos="$wm_infos $layout"
        	                ;;

			esac
			shift
		done
	;;
	esac

	printf "%s\n" "%{l}$wm_infos %{r}$(network) $DIV $(F $ram_icon $GREEN) $(freeram) $DIV $(F $tmp_icon $GREEN) $(cputemp) $DIV $(F $pac_icon $GREEN) $(checkupdates) $DIV $(F $vol_icon $GREEN) $(volume) $DIV $TIME $DATE "
done
