#!/bin/bash

source $(dirname $0)/panel_config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    pkill -o panel
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
clock -i5 -sf 'C%H:%M' > "$PANEL_FIFO" &
xtitle -t130 -sf 'T%s' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ./panel_bar | bar -g $PANEL_GEOMETRY -u 3 -f "$PANEL_FONT_FAMILY" -F "$CLR_FG" -B "$CLR_BG" | while read line; do eval "$line"; done &

wait
