#!/bin/bash

# Height of underlines / overlines
LINEHEIGHT="3"

function A {
        echo -n "%{A:$2:}$1%{A}"
}

function B {
        echo -n "%{B#ff$2}$1%{B-}"
}

function F {
        echo -n "%{F#ff$2}$1%{F-}"
}

function o {
        echo "%{+o}$1%{-o}"
}

function u {
        echo "%{+u}$1%{-u}"
}



DIV=$(F '|' $GRAY)

###

network() {
        ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo -n $(F + $GREEN) || echo -n $(F - $RED)
}


volume() {
        VOLUME=$(pamixer --get-volume)
        if [[ $(pamixer --get-mute) -eq 'true' ]]
        then
                VCOLOR=$WHITE
        else
                VCOLOR=$GRAY
        fi
        echo -n "$(A $(F $VOLUME $VCOLOR) volume)"
}

freeram() {
        USED=$(free -m | awk 'NR == 2 {gsub(/%/,""); print $3}')
        USED+="MB"
        echo -n $(F $USED $WHITE)
}
checkupdates() {
        CHK=$(pacman -Qu | wc -l)
        echo -n $(F $CHK $WHITE)
}

cputemp() {
        CPUTMP=$((`sensors | grep "Physical id 0" | cut -d'+' -f2 | head -c2`))
        echo -n $(F $CPUTMP $WHITE)
}


