#! /bin/sh

bspc config border_width        1
bspc config window_gap         10
bspc config top_padding        12
bspc config left_padding       0
bspc config bottom_padding     18
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d Home Web Code Files Torrent Read Misc 

bspc rule -a Gimp desktop=^7 follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a Transmission-gtk desktop=^5
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off

## autostart
feh --bg-scale /home/dean/Pictures/poly.jpg &
compton --vsync opengl-swc --shadow-exclude 'n:a:Conky' -b &
conky &
run_once /opt/dropbox/dropboxd
run_once mpd
/home/dean/.config/bspwm/panel &
