#! /bin/sh

bspc config border_width        1
bspc config window_gap         10
bspc config top_padding        26
bspc config left_padding       0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor \
	        -n "$i" \
	        -d $i/{i,ii,iii,iv,v}
    let i++
done
NMON=$i
unset i


bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a Steam desktop=^3 follow=on
bspc rule -a Gimp desktop=^5 follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a mutt desktop=^5
bspc rule -a ranger desktop=^4

## autostart
unclutter -root -idle 1 &
feh --bg-scale /home/dean/Pictures/poly.jpg &
compton --vsync opengl-swc --shadow-exclude 'n:a:Conky' -b &
# conky &
/opt/dropbox/dropboxd &
mpd &
cd /home/dean/.config/bspwm/panel/ && ./panel &
