#! /bin/sh

bspc config border_width        1
bspc config window_gap         10
bspc config top_padding        12
bspc config left_padding       0
bspc config bottom_padding     18
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true


bspc monitor -d Home Web Code Files Torrent Read Misc

bspc desktop ^1 -l tiling 
bspc desktop ^2 -l tiling
bspc desktop ^3 -l tiling
bspc desktop ^4 -l tiling
bspc desktop ^5 -l tiling
bspc desktop ^6 -l tiling
bspc desktop ^7 -l tiling

bspc rule -a Gimp desktop=^7 follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a mutt desktop=^6
bspc rule -a ranger desktop=^4

## autostart
unclutter -root -idle 1 &
feh --bg-scale /home/dean/Pictures/poly.jpg &
compton --vsync opengl-swc --shadow-exclude 'n:a:Conky' -b &
conky &
/opt/dropbox/dropboxd &
mpd &
/home/dean/.config/bspwm/panel &
